### ISSUE TITLE
Raft

### ISSUE THREAD

**Issue by hello23dev** [donovan6000/M3D-Fio#100]
Hello, my problem is that when I print with the M3D software the raft is very easy to take from the model, when I print with octoprint with M3D-Fio it's impossible to take the raft from the model. I would be thankful is somebody could help me because I think is absolutely useful to 3D print without having my computer plugged in.

**Comment by donovan6000** [comment]
You can increase the the raft airgap in the manual section of the slicer profile editor which increases the distance between the raft and the model. That should make it easier to separate the model from the raft.
![airgap](https://cloud.githubusercontent.com/assets/6620767/13382871/8ae735f0-de33-11e5-8753-2664749ae856.png)
