### ISSUE TITLE
Add option to skip 3D model preview

### ISSUE THREAD

**Issue by abbradar** [donovan6000/M3D-Fio#114]
Usecase: a very big and detailed model, which eats ~3GB RAM in the viewer (and a minute or so to load), and that's on a pretty high-end machine! That's a model fault (it's really detailed, for example Blender also takes time to load it).

**Comment by donovan6000** [comment]
Ok, the devel branch now allows skipping the model editor.
![skip](https://cloud.githubusercontent.com/assets/6620767/13726498/5c6d2720-e87e-11e5-9877-2f0aefaa882f.png)

**Comment by beth21762** [comment]
Can I just say you are awesome!!!  Your quick responses to fixing issues and request for everyone is just unbelievable!!  I truly appreciate all of the help you have given me so far and that I know I will be asking for more in the future.  ;)

**Comment by abbradar** [comment]
I very much second @beth21762. ~_^ Thanks for quick responses and for your commitment to fix issues.

**Comment by donovan6000** [comment]
Thanks everyone! Glad I can help :)
