### ISSUE TITLE
Manual and advanced slicing settings are unusable

### ISSUE THREAD

**Issue by LogicalChaos** [donovan6000/M3D-Fio#123]
Running Safari Version 9.0.3 (11601.4.4).  See screenshot.  The space for the two mentioned areas are virtually unusable.  The manual settings can be tabbed through to change then, the advanced settings text box can be 'seen', but barely.  The popup window cannot be resized to expose them further.
![screenshot 2016-03-26 11 30 43](https://cloud.githubusercontent.com/assets/6620274/14061488/cb06f7ec-f346-11e5-9ec1-3947dab5a533.png)

**Comment by donovan6000** [comment]
Right now I'm only maintaining M3D Fio's compatibility with Google Chrome and Firefox. I don't have any computers that can run OS X >= 10.9 which is required for using the newest version of Safari, so there's not much I can do myself to make everything in M3D Fio compatible with it.

**Comment by LogicalChaos** [comment]
Ahhh, launching in Chrome, I noticed to the left of the text are dialog expansion buttons ![screenshot 2016-03-27 11 30 14](https://cloud.githubusercontent.com/assets/6620274/14066745/78fde19e-f40f-11e5-905d-ab8a54cbbddd.png).  If you click in that area on Safari, they work.
