### ISSUE TITLE
Permission denied for /octoprint_m3dfio/static/temp/

### ISSUE THREAD

**Issue by ra100** [donovan6000/M3D-Fio#13]
I am/was getting this error `OSError: [Errno 13] Permission denied: '/usr/local/lib/python2.7/dist-packages/OctoPrint_M3DFio-0.22-py2.7.egg/octoprint_m3dfio/static/temp/'`

I fixed it, for now, by creating temp folder and setting permissions to 777. But I think, this shouldn't work that way. I'm not running octoprint asi root but asi user "pi" with root privileges.

**Comment by donovan6000** [comment]
Sorry, I was trying out some new stuff and didn't fully test it before pushing it to GitHub. I reworked it so that it doesn't use a temp folder.

**Comment by ra100** [comment]
It's fine, I have no problem with testing and reporting.
