### ISSUE TITLE
Invalid Z0

### ISSUE THREAD

**Issue by CatSailer1279** [donovan6000/M3D-Fio#134]
Hi,
first of all I want to thank you for your Octoprint Plugin. It´s great!

Yesterday I updated from 0.31 to 0.32. Since the update Octoprint looses on every restart the value of Z0 and I have to recalibrate Z0. ("Calibrate before print C" is deactivated)
Firmware is M3D firmware V2016040401 and version of Octoprint 1.2.10.

Does anyone has an idea what´s wrong?

**Comment by donovan6000** [comment]
Try installing the V2016010812 firmware from the Advanced section of the controls tab and see if that helps. I've had a lot of weird Z issues with M3D's V2016040401 firmware.

**Comment by CatSailer1279** [comment]
Thx for advise. I will test it.
