### ISSUE TITLE
octoprint calibration offset (z-axis)

### ISSUE THREAD

**Issue by 3dfan** [donovan6000/M3D-Fio#18]
Hello

My octopi + micro3d setup is almost working fine. It seems the automatic calibration is a bit off and the print is not sticking to the board.
Can I somehow manually offset the z0 in octoprint (like you can on the native micro3d software) ?

On the octoprint forum they suggested to make a custom gcode control, but they had doubts how this would integrate with the custom plugin for the Micro ...

Any suggestions welcome.

thx for helping out :)

**Comment by donovan6000** [comment]
In OctoPrint's settings under the M3D Fio tab there's a setting called 'Bed Height Offset' which does what your looking for. All the 'offset' settings are equivalent to the official software's cat bed leveling screen settings.

**Comment by 3dfan** [comment]
coool !!!
thank you very much, I will check it tonight :D

**Comment by briankb** [comment]
is that option available for any printer profile or is it a plugin specifically for M3D? I need to adjust the z-height as well for the same reason on my prusa i3 clone. ideally a Global Z-Height offset would be available per printer profile
