### ISSUE TITLE
Modifications made in 3D preview are ignored

### ISSUE THREAD

**Issue by npag** [donovan6000/M3D-Fio#35]
When applying changes to the model position on the printbed the printer will ignore this changes and print the model in the original place.

**Comment by donovan6000** [comment]
It should be fixed now. Also make sure that the 'Center Model' pre-processor is disabled in OctoPrint's settings under the M3D Fio tab.

**Comment by npag** [comment]
I'll be able to take a look later this week. Giving feedback soon!

**Comment by npag** [comment]
I need to reinstall octoprint I guess. My pip installation has gone missing and I am not able to update octoprint to 1.2.8 either. I will test your fix next week.

**Comment by npag** [comment]
I figured out my issues with OctoPrint and tested your modifications. Works great now, thank you very much!
