### ISSUE TITLE
High memory usage on model preparation

### ISSUE THREAD

**Issue by ra100** [donovan6000/M3D-Fio#39]
When trying to slice large model 3MB and more, the memory usage is over 250 MB, which can be sometimes problem on Raspberry Pi. I tried 3MB and 4MB model, and both consumed about same ammout of memory, with 1MB it has been much less. I didn't do any exact measurements, just watched htop after hittin "Slice", most memory usage was while "Applying changes" phase.
It is not as issue as suggestion for performance improvement.

![large model](https://cloud.githubusercontent.com/assets/3185410/12221647/2d1de906-b7a4-11e5-89f1-4c5847d40ccc.png)

**Comment by donovan6000** [comment]
Should be fixed now.

I'm not really sure why the method I was using to upload the files was causing such high ram usage, but switching to the method that OctoPrint uses when uploading files seems to have fixed it.

**Comment by ra100** [comment]
Works like a charm :)
