### ISSUE TITLE
[Suggestion] Add plugin to the OctoPrint Plugin Repository

### ISSUE THREAD

**Issue by foosel** [donovan6000/M3D-Fio#41]
Hey,

It would be great if you added that plugin to [plugins.octoprint.org](http://plugins.octoprint.org/) - unless there's a particular reason that is not possible? 

Instructions can be found [here](http://plugins.octoprint.org/help/registering/) - you'll basically just have to clone a repository and add a file to it. If you don't want to, I could also add it, just don't want to add any plugins without asking the authors first.

Cheers,
Gina :octopus:

**Comment by donovan6000** [comment]
Sounds good with me. Just submitted the [pull request](https://github.com/OctoPrint/plugins.octoprint.org/pull/29)

**Comment by foosel** [comment]
And merged :)
