### ISSUE TITLE
Octoprint API integration?

### ISSUE THREAD

**Issue by Matthew-Bradley** [donovan6000/M3D-Fio#44]
It would be very helpful if the readme specified whether this plugin makes changes to the octoprint API.

It brings many great features to the slicing functionality, like rotation of the model and other options, and it would be great if they were accessible in the API if they aren't already.

**Comment by donovan6000** [comment]
M3D Fio doesn't make any changes to OctoPrint's API. I honestly don't understand enough about Python to even know how to start making it accessible by the API.
