### ISSUE TITLE
install.sh script installs newest (unstable) version

### ISSUE THREAD

**Issue by drschlaumeier** [donovan6000/M3D-Fio#50]
wget https://github.com/donovan6000/M3D-Fio/archive/master.zip

downloads the newest version but not the latest stable version...
why not using

wget https://github.com/donovan6000/M3D-Fio/archive/0.24.3.zip

**Comment by ra100** [comment]
Or maybe create devel branch? So in master is always latest stable version.

**Comment by drschlaumeier** [comment]
> So in master is always latest stable version.
Are you sure? When I do "pip install https://github.com/donovan6000/M3D-Fio/archive/master.zip" I get all the latest commits installed ... probably untested?
I mean when I do the intall today I get something different when I do the intall tomorrow...

**Comment by donovan6000** [comment]
Ok, devel branch has been created.

Some new code was just pushed to the master branch that could make it more stable. I've never done any M3D Fio testing on a network or on a Raspberry Pi, and I feel like a majority of issues are related to how those things are configured.

**Comment by LogicalChaos** [comment]
FYI:  I'm only using a Raspberry Pi, OctoPi based.  Maybe that was apparent from other issues :-)
