### ISSUE TITLE
M3D stops printing after ~6h

### ISSUE THREAD

**Issue by Finkes** [donovan6000/M3D-Fio#54]
I have been printing a relative big model for over 6h but then the printer just stops moving. I was still heating and octoprint seams to send the commands to the printer but for some reason the printer ignores those commands. I tried it another time and again after more then 6h the same issue happened. However this time the printer printer the model a bit longer then the first time. Does someone know what could be going in here? I know that this might be an issue with the printer itself or with octoprint but since octoprint is not supported by the official m3d team, this project is my only hope for a solution.

**Comment by donovan6000** [comment]
Try out the newest release, V0.25. This issue might be related to #43 which got fixed.

**Comment by Finkes** [comment]
It's working now with V0.25. Super awesome :-) thanks! Keep it going!
