### ISSUE TITLE
Feature Request: please provide gcode without bed compensation for the gcode viewer but with for printing

### ISSUE THREAD

**Issue by mrvn** [donovan6000/M3D-Fio#6]
Loading bed compensated gcode view in octoprint is completly useless because it things every z correction is it's own layer. And switching off bed correction for preview and on again for print is a lot of extra work and easy to forget to turn it back on. The plugin should save the gcode without bed correction for the viewer and with for printing.

**Comment by dragondgold** [comment]
The built-in G-Code Viewer renders the selected file to print, so I don't think there is a way to view it correctly. A workaround could be to save the save both g-codes, the original and the processed one with some prefix like "processed_<filename>" so you could view the original g-code and print the processed one. 

Or you can just view the model in your computer and then send it to octoprint. I use Slic3r and it has a built-in octoprint support so you can send the g-code to your printer in just one click.

**Comment by mrvn** [comment]
Actually there is, you just have to use different hooks.

What I mean is that there is a hook that gets called when gcode gets send to the printer and you can modify the gcode then. So bed leveling should not be done during slicing but during printing on the fly. The same would apply to backlash compensation.

**Comment by donovan6000** [comment]
Implemented an on the fly G-code pre-processing settings in the latest release, V0.22, which allows OctoPrint's G-code viewer to work as expected.

**Comment by dragondgold** [comment]
This should be closed now!
