### ISSUE TITLE
M3D will stop on Raspberry Pi

### ISSUE THREAD

**Issue by mdikov** [donovan6000/M3D-Fio#61]
I tried several models that print without a problem on M3D default software. When I print via Octoprint on Raspberry Pi , the raft or the brim print fine than the printer will start the first layer and stop before it's done. The GCode viewer and terminal continue to send commands.

I also tried gcode generated on another Cura and the same happens.

**Comment by tobiasbischoff** [comment]
Yes i have that too. But it seems model independent. I can try to send the exact same gcode to the printer - first time the m3d stopps at 60%, second time it justs prints thru fine.

**Comment by mdikov** [comment]
Is it possible that the  serial connection drops? The interesting part is that the printer seems to be responding to the commands in terminal. Maybe a firmware or gcode incompatibility?

**Comment by totterfree** [comment]
I can confirm this same issue. I'm using the raspberry pi zero. Both the Pi and the M3D are connected to a reliable power source. The M3D is connected to the Pi via a usb hub which also has a wifi adapter connected. I have had the printer freeze on all of my prints so far. I will check for any terminal output on my next attempt

**Comment by donovan6000** [comment]
I don't own or have access to a Raspberry Pi, and it's difficult for me to fix issues that I can't recreate. Can any of you provide an OctoPrint log of when this happens? It's located at ~/.octoprint/logs/octoprint.log.

**Comment by tobiasbischoff** [comment]
Actually it has been quite some time that this happend to me. Since i upgraded to 25 it happened once, then never again. Although i have tons of other problems with the m3d now, like skipping, not sticking to bed etc, overall bad print quality. Its that much that i'm pretty much fed up with it.

**Comment by mdikov** [comment]
I can provide my latest logs later in the week.

**Comment by donovan6000** [comment]
Make sure your using M3D Fio's latest [devel build](https://github.com/donovan6000/M3D-Fio/tree/devel) when testing this issue so I can see if it hasn't been fixed yet. You can install using OctoPrint's plugin manager by installing a plugin from the following URL:
`https://github.com/donovan6000/M3D-Fio/archive/devel.zip`

**Comment by mdikov** [comment]
Here you go. I started the model and got one or two layers then just
stopped.

**Comment by mdikov** [comment]
Also to confirm I upgraded to 0.26 from the develop branch.

Here is what comes out of the terminal:

Recv: ok 1274
Send: N1275 G1 X60.799934 Y55.368109 Z0.366256 E60.247521**20
Recv: ok 1275
Send: N1276 G1 X61.582902 Y57.208478 Z0.372373 E60.276624**26
Recv: ok 1276
Send: N1277 G1 X62.431028 Y59.202000 Z0.378975 E60.30815**37
Recv: ok 1277
Send: N1278 G1 X62.365 Y58.195 E60.31230*111
Recv: ok 1278
Send: N1279 G1 X62.711028 Y58.195000 Z0.375589 E60.31230 F780**113
Recv: ok 1279
Send: N1280 G1 X62.365 Y43.770 E60.52221*106
Recv: ok 1280
Send: N1281 G1 X62.711028 Y54.195000 Z0.344275 E60.370507**16
Recv: ok 1281
Send: N1282 G1 X62.711028 Y52.195000 Z0.328618 E60.399611**19
Recv: ok 1282
Send: N1283 G1 X62.711028 Y50.195000 Z0.312962 E60.428715**19
Recv: ok 1283
Send: N1284 G1 X62.711028 Y48.195000 Z0.297305 E60.457818**16
Recv: ok 1284
Send: N1285 G1 X62.711028 Y46.195000 Z0.281648 E60.486922**16
Recv: ok 1285
Send: N1286 G1 X62.711028 Y43.770000 Z0.262664 E60.52221**45
Recv: T:208.9900
Recv: ok 1286
Send: N1287 G1 X67.465 Y43.770 E60.59642*101
Recv: ok 1287
Send: N1288 G1 X67.811028 Y43.770000 Z0.208668 E60.59642**35
Recv: ok 1288
Send: N1289 G0 F3000 X66.528 Y44.592*126
Recv: ok 1289
Send: N1290 G0 X66.528000 Y45.542000 Z0.225023 F3000**48
Recv: ok 1290
Send: N1291 G1 F780 X63.187 Y47.934 E60.66518*60
Recv: ok 1291
Send: N1292 G1 X63.187000 Y48.884000 Z0.286559 E60.66518 F780**113
Recv: ok 1292
Send: N1293 G0 F3000 X63.187 Y48.429*124
Recv: ok 1293
Send: N1294 G1 F780 X66.641 Y44.975 E60.73626*61
Recv: T:215.0885
Recv: ok 1294
Send: N1295 G1 X64.947242 Y47.014786 Z0.264390 E60.694283 F780**71
Recv: ok 1295
Send: N1296 G1 X66.987028 Y44.975000 Z0.226825 E60.73626 F780**119
Recv: ok 1296
Send: N1297 G0 F3000 X66.641 Y45.470*113
Recv: ok 1297
Send: N1298 G0 X66.987028 Y46.420000 Z0.230700 F3000**63
Recv: ok 1298
Send: N1299 G1 F780 X63.187 Y48.924 E60.80734*62
Recv: ok 1299
Send: N1300 G1 X65.226786 Y47.834214 Z0.256744 E60.765363 F780**66
Recv: T:208.9900
Recv: ok 1300
Send: N1301 G1 X63.187000 Y49.874000 Z0.294309 E60.80734 F780**112
Recv: ok 1301
Send: N1302 G0 F3000 X63.187 Y49.419*119
Recv: ok 1302
Send: N1303 M105*22
Recv: ok 1303
Send: N1304 G1 F780 X66.641 Y45.965 E60.87842*50
Recv: ok 1304
Send: N1305 G1 X64.947242 Y48.004786 Z0.272140 E60.836443 F780**69
Recv: ok 1305
Send: N1306 G1 X66.987028 Y45.965000 Z0.234575 E60.87842 F780**115
Recv: ok 1306
Send: N1307 G0 F3000 X66.641 Y46.460*123
Recv: ok 1307
Send: N1308 G0 X66.987028 Y47.410000 Z0.238450 F3000**59
Recv: ok 1308
Send: N1309 G1 F780 X63.187 Y49.914 E60.94950*61
Recv: ok 1309
Send: N1310 G1 X65.226786 Y48.824214 Z0.264494 E60.907523 F780**74
Recv: ok 1310
Send: N1311 G1 X63.187000 Y50.864000 Z0.302059 E60.94950 F780**121
Recv: ok 1311
Send: N1312 G0 F3000 X63.187 Y50.409*127
Recv: ok 1312
Send: N1313 G1 F780 X66.641 Y46.955 E61.02057*52
Recv: ok 1313
Send: N1314 G1 X64.947242 Y48.994786 Z0.279890 E60.978599 F780**71
Recv: ok 1314
Send: N1315 G1 X66.987028 Y46.955000 Z0.242325 E61.02057 F780**115
Recv: ok 1315
Send: N1316 G0 F3000 X66.641 Y47.450*121
Recv: ok 1316
Send: N1317 G0 X66.987028 Y48.400000 Z0.246200 F3000**49
Recv: ok 1317
Send: N1318 G1 F780 X63.187 Y50.904 E61.09165*63
Recv: T:208.9900
Recv: ok 1318
Send: N1319 G1 X65.226786 Y49.814214 Z0.272244 E61.049673 F780**73
Recv: ok 1319
Send: N1320 G1 X63.187000 Y51.854000 Z0.309809 E61.09165 F780**116
Recv: ok 1320
Send: N1321 G0 F3000 X63.187 Y51.399*112
Recv: ok 1321
Send: N1322 G1 F780 X66.641 Y47.945 E61.16273*55
Recv: ok 1322
Send: N1323 G1 X64.947242 Y49.984786 Z0.287640 E61.120753 F780**65
Recv: ok 1323
Send: N1324 G1 X66.987028 Y47.945000 Z0.250075 E61.16273 F780**117
Recv: ok 1324
Send: N1325 G0 F3000 X66.641 Y48.440*119
Recv: ok 1325
Send: N1326 G0 X66.987028 Y49.390000 Z0.253950 F3000**54
Recv: ok 1326
Send: N1327 G1 F780 X63.187 Y51.894 E61.23381*58
Recv: T:215.0885
Recv: ok 1327
Send: N1328 G1 X65.226786 Y50.804214 Z0.279994 E61.191833 F780**65
Recv: ok 1328
Send: N1329 G1 X63.187000 Y52.844000 Z0.317559 E61.23381 F780**120
Recv: ok 1329
Send: N1330 G0 F3000 X63.187 Y52.389*114
Recv: ok 1330
Send: N1331 G1 F780 X66.641 Y48.935 E61.30489*58
Recv: ok 1331
Send: N1332 G1 X64.947242 Y50.974786 Z0.295390 E61.262913 F780**66
Recv: ok 1332
Send: N1333 G1 X66.987028 Y48.935000 Z0.257825 E61.30489 F780**118
Recv: ok 1333
Send: N1334 G0 F3000 X66.641 Y49.430*113
Recv: ok 1334
Send: N1335 G0 X66.987028 Y50.380000 Z0.261700 F3000**55
Recv: ok 1335
Send: N1336 G1 F780 X63.187 Y52.884 E61.37597*60
Recv: ok 1336
Send: N1337 G1 X65.226786 Y51.794214 Z0.287744 E61.333993 F780**75
Recv: T:208.9900
Recv: ok 1337
Send: N1338 G1 X63.187000 Y53.834000 Z0.325309 E61.37597 F780**120
Recv: ok 1338
Send: N1339 G0 F3000 X63.187 Y53.379*117
Recv: ok 1339
Send: N1340 G1 F780 X66.641 Y49.925 E61.44705*56
Recv: ok 1340
Send: N1341 G1 X64.947242 Y51.964786 Z0.303140 E61.405073 F780**79
Recv: ok 1341
Send: N1342 G1 X66.987028 Y49.925000 Z0.265575 E61.44705 F780**125
Recv: ok 1342
Send: N1343 G0 F3000 X66.641 Y50.420*120
Recv: ok 1343
Send: N1344 G0 X66.987028 Y51.370000 Z0.269450 F3000**49
Recv: ok 1344
Send: N1345 G1 F780 X63.187 Y53.874 E61.51813*55
Recv: ok 1345
Send: N1346 G1 X65.226786 Y52.784214 Z0.295495 E61.476153 F780**65
Recv: T:215.0885
Recv: ok 1346
Send: N1347 G1 X63.187000 Y54.824000 Z0.333059 E61.51813 F780**118
Recv: ok 1347
Send: N1348 M105*25
Recv: T:208.9900
Recv: ok 1348
Send: N1349 G0 F3000 X63.187 Y54.369*116
Recv: ok 1349
Send: N1350 G1 F780 X66.641 Y50.915 E61.58920*54
Recv: ok 1350
Send: N1351 G1 X64.947242 Y52.954786 Z0.310890 E61.547229 F780**66
Recv: ok 1351
Send: N1352 G1 X66.987028 Y50.915000 Z0.273326 E61.58920 F780**116
Recv: ok 1352
Send: N1353 G0 F3000 X66.641 Y51.410*123
Recv: ok 1353
Send: N1354 G0 X66.987028 Y52.360000 Z0.277201 F3000**63
Recv: ok 1354
Send: N1355 G1 F780 X63.187 Y54.864 E61.66028*52
Recv: ok 1355
Send: N1356 G1 X65.226786 Y53.774214 Z0.303245 E61.618303 F780**70
Recv: ok 1356
Send: N1357 G1 X63.187000 Y55.814000 Z0.340809 E61.66028 F780**120
Recv: ok 1357
Send: N1358 G0 F3000 X63.187 Y55.359*118
Recv: ok 1358
Send: N1359 G1 F780 X66.641 Y51.905 E61.73136*57
Recv: ok 1359
Send: N1360 G1 X64.947242 Y53.944786 Z0.318640 E61.689383 F780**75
Recv: ok 1360
Send: N1361 G1 X66.987028 Y51.905000 Z0.281076 E61.73136 F780**121
Recv: ok 1361
Send: N1362 G0 F3000 X66.641 Y52.400*123
Recv: ok 1362
Send: N1363 G0 X66.987028 Y53.350000 Z0.284951 F3000**59
Recv: ok 1363
Send: N1364 G1 F780 X63.187 Y55.854 E61.80244*52
Recv: T:215.0885
Recv: ok 1364
Send: N1365 G1 X65.226786 Y54.764214 Z0.310995 E61.760463 F780**75
Recv: ok 1365
Send: N1366 G1 X63.187000 Y56.804000 Z0.348559 E61.80244 F780**120
Recv: ok 1366
Send: N1367 M117 [          ]   1%%*32
Recv: e1
Recv: T:208.9900
Recv: wait

=============this is where it stops ============
Send: N1368 G0 F3000 X63.187 Y56.349*119
Recv: T:208.4817
Recv: wait
Recv: T:215.8991
Recv: wait
Recv: T:215.8991
Recv: wait
Recv: T:215.8991
Recv: wait

**Comment by donovan6000** [comment]
@mdikov The problem is that the M117 command is used to display stuff on an LCD screen, and M3D's firmware doesn't recognize that command so it returns an error, e1. M3D Fio waits for an 'ok' response before sending the next command, so it's never able to send the next command which causes the print to stop.

The latest change to the devel branch [adds M117 to list of commands that M3D Fio's validation pre-processor removes](https://github.com/donovan6000/M3D-Fio/commit/cec93d7addac7856f2243d0c686d4b2968300458), so it should be able to print now.

**Comment by mdikov** [comment]
Great. I'll check it out. 

Just curious why would cura add this command? Perhaps there's a way turn this off in the cura profile.

**Comment by donovan6000** [comment]
@mdikov The M117 command is probably in the Cura profile's start or end G-code, which is why it gets added in.

**Comment by mdikov** [comment]
Thank you @donovan6000! Works great now.
