### ISSUE TITLE
Can't install on OctoPi nightly 0.13.0

### ISSUE THREAD

**Issue by guysoft** [donovan6000/M3D-Fio#63]
Hey,
I tried installing M3D Fio on the most recent Nightly today 2016-01-31_2015-11-21-octopi-jessie-lite-0.13.0.zip . Although the python package seems to install fine, I don't see any settings for the m3d, also the plugin is not listed in the plugin manager. I can search and install it again.

```
pi@octopi:~ $ /home/pi/oprint/bin/pip install https://github.com/donovan6000/M3D-Fio/archive/master.zip
Collecting https://github.com/donovan6000/M3D-Fio/archive/master.zip
  Downloading https://github.com/donovan6000/M3D-Fio/archive/master.zip (4.8MB)
    100% |████████████████████████████████| 4.8MB 11kB/s 
  Requirement already satisfied (use --upgrade to upgrade): OctoPrint-M3DFio==0.25 from https://github.com/donovan6000/M3D-Fio/archive/master.zip in ./oprint/lib/python2.7/site-packages
```

Am I missing something?

**Comment by guysoft** [comment]
Hey, tried installing and installing, and saw I get this in the GUI: 
![fail5](https://cloud.githubusercontent.com/assets/325670/12704913/50ddada6-c86e-11e5-8cf5-ac57fb7f6067.png)

**Comment by tenitram** [comment]
Had the same issue - in my case it was python-dbus package missing - check octoprint log file

**Comment by donovan6000** [comment]
Can you install the devel branch? https://github.com/donovan6000/M3D-Fio/archive/devel.zip

**Comment by guysoft** [comment]
ok @tenitram was right, I had to install python dbus on the virtualenv, which can't be done now by simple apt-get.
So what needs to be done is:

```
sudo apt-get build-dep python-dbus
/home/pi/oprint/bin/pip install -U git+https://github.com/posborne/dbus-python.git
```

**Comment by donovan6000** [comment]
I just tested out installing and running the devel branch without having Python DBus installed and it worked without any issues, so the next release will be able to run without needing Python DBus installed.
