### ISSUE TITLE
Freeze on calibrating Z0 (Raspberry Pi/Octoprint)

### ISSUE THREAD

**Issue by jctj** [donovan6000/M3D-Fio#80]
Using your excellent work, I have a Mac pushing to a Raspberry Pi 2 that controls the M3D via Octoprint. I have finally gotten things *almost* working, but whenever I calibrate via Octoprint, the website freezes (left it running for 30+ min) and I have to unplug everything. Had to move the head manually to change ink, and can't get Octoprint to see that the M3D is down and centered. 

I have gotten Octoprint to initiate the calibration and the head goes back to grind, right to grind, back to center, and then down to the bed with some up/down action going on, but then the M3D printer does nothing and the Octoprint website keeps the "calibration is process" warning up. 

And thank you so much for what you are doing - M3D is nearly worthless on a Mac and the Pi is a perfect server.

**Comment by donovan6000** [comment]
What does OctoPrint's terminal tab show when this happens? You won't be able to go to that tab when the 'calibration in progress' message is showing, you'll need to refresh the webpage and then go to the controls tab.

**Comment by jctj** [comment]
I fired everything back up again. Delays are unbelievable - as in it takes 10 min for Octopi.local/ to be able to successfully load (lots of failed attempts before it finally works, doing nothing but hitting the reload button all the while). Once it was ready, I checked terminal and it had: 
emperature
Control
GCode Viewer
Terminal
Timelapse
Send: M619 S41 T1
Recv: ok  PT:40 DT:67
Send: M619 S70 T4
Recv: ok  PT:41 DT:165
Send: M619 S74 T4
Recv: ok  PT:70 DT:0
Send: M619 S78 T4
Recv: ok  PT:74 DT:0
Send: M619 S82 T4
Recv: ok  PT:78 DT:0
Recv: ok  PT:82 DT:0
Send: M619 S86 T4
Send: M619 S94 T4
Recv: ok  PT:86 DT:0
Send: M619 S102 T4
Recv: ok  PT:94 DT:1153138688
Send: M619 S106 T4
Recv: ok  PT:102 DT:1153138688
Send: M619 S110 T4
Recv: ok  PT:106 DT:1153138688
Send: M619 S114 T4
Recv: ok  PT:110 DT:1114636288
Send: M619 S118 T4
Recv: ok  PT:114 DT:1120665600
Send: M619 S98 T1
Recv: ok  PT:118 DT:1135869952
Send: M420 T100
Recv: ok  PT:98 DT:1
Recv: ok
Recv: wait
Send: M105
Recv: ok
Recv: T:0
Recv: wait
Changing monitoring state from 'Operational' to 'Closed'
Connection closed, closing down monitor
Changing monitoring state from 'Offline' to 'Detecting serial port'
Connecting to: /dev/ttyACM0
Changing monitoring state from 'Detecting serial port' to 'Opening serial port'
Connected to: Serial<id=0x1fc0b30, open=True>(port='/dev/ttyACM0', baudrate=115200, bytesize=8, parity='N', stopbits=1, timeout=None, xonxoff=False, rtscts=False, dsrdtr=False), starting monitor
Starting baud rate detection
Changing monitoring state from 'Opening serial port' to 'Detecting baudrate'
Trying baudrate: 250000
Send: M110
Recv: e1
Changing monitoring state from 'Detecting baudrate' to 'Closed'
Changing monitoring state from 'Offline' to 'Detecting serial port'
Connection closed, closing down monitor
Connecting to: /dev/ttyACM0
Changing monitoring state from 'Detecting serial port' to 'Opening serial port'
Connected to: Serial<id=0x2299270, open=True>(port='/dev/ttyACM0', baudrate=115200, bytesize=8, parity='N', stopbits=1, timeout=None, xonxoff=False, rtscts=False, dsrdtr=False), starting monitor
Starting baud rate detection
Changing monitoring state from 'Opening serial port' to 'Detecting baudrate'
Recv: e1
Recv: wait
Trying baudrate: 250000
Send: M110
Recv: e1
Recv: e1
Recv: ok
Changing monitoring state from 'Detecting baudrate' to 'Operational'
Send: M21
Unexpected error while writing to serial port: SerialException: 'write failed: [Errno 5] Input/output error' @ comm.py:_doSendWithoutChecksum:1752
Connection closed, closing down monitor
Changing monitoring state from 'Operational' to 'Error: SerialException: 'write failed: [Errno 5] Input/output error' @ comm.py:_doSendWithoutChecksum:1752'
Closing down send loop
Connecting to: /dev/ttyACM1
Changing monitoring state from 'Offline' to 'Opening serial port'
Connected to: Serial<id=0x221fb10, open=True>(port='/dev/ttyACM1', baudrate=115200, bytesize=8, parity='N', stopbits=1, timeout=None, xonxoff=False, rtscts=False, dsrdtr=False), starting monitor
Changing monitoring state from 'Opening serial port' to 'Connecting'
Send: M110
Unexpected error while reading serial port, please consult octoprint.log for details: SerialException: 'device reports readiness to read but returned no data (device disconnected or multiple access on port?)' @ comm.py:_readline:1419
Changing monitoring state from 'Connecting' to 'Error: SerialException: 'device reports readiness to read but returned no data (device disconnected or multiple access on port?)' @ comm.py:_readline:1419'
Connection closed, closing down monitor
Connecting to: /dev/ttyACM0
Changing monitoring state from 'Offline' to 'Opening serial port'
Connected to: Serial<id=0x221f1f0, open=True>(port='/dev/ttyACM0', baudrate=115200, bytesize=8, parity='N', stopbits=1, timeout=None, xonxoff=False, rtscts=False, dsrdtr=False), starting monitor
Changing monitoring state from 'Opening serial port' to 'Connecting'
Send: M110
Recv: e1
Recv: ok REPETIER_PROTOCOL:2 FIRMWARE_NAME:Micro3D FIRMWARE_VERSION:2016012501 MACHINE_TYPE:The_Micro X-SERIAL_NUMBER:GR15061901050040
Changing monitoring state from 'Connecting' to 'Operational'
Send: M105
Send: M21
Recv: ok
Recv: T:0
Send: M117
Recv: ok ZV:0 S:128
Send: M114
Recv: ok  Z:0.0000
Send: M619 S12 T4
Send: M619 S16 T4
Recv: ok  PT:12 DT:1054905749
Send: M619 S20 T4
Recv: ok  PT:16 DT:1058642330
Send: M619 S24 T4
Recv: ok  PT:20 DT:1024106757
Send: M619 S28 T4
Recv: ok  PT:24 DT:1059309502
Send: M619 S32 T4
Recv: ok  PT:28 DT:-1087395415
Send: M619 S40 T1
Recv: ok  PT:32 DT:-1077801397
Send: M619 S41 T1
Recv: ok  PT:40 DT:67
Send: M619 S70 T4
Recv: ok  PT:41 DT:165
Send: M619 S74 T4
Recv: ok  PT:70 DT:0
Send: M619 S78 T4
Recv: ok  PT:74 DT:0
Send: M619 S82 T4
Recv: ok  PT:78 DT:0
Send: M619 S86 T4
Recv: ok  PT:82 DT:0
Send: M619 S94 T4
Recv: ok  PT:86 DT:0
Send: M619 S102 T4
Recv: ok  PT:94 DT:1153138688
Send: M619 S106 T4
Recv: ok  PT:102 DT:1153138688
Send: M619 S110 T4
Recv: ok  PT:106 DT:1153138688
Send: M619 S114 T4
Recv: ok  PT:110 DT:1114636288
Send: M619 S118 T4
Recv: ok  PT:114 DT:1120665600
Send: M619 S98 T1
Recv: ok  PT:118 DT:1135869952
Send: M420 T100
Recv: ok  PT:98 DT:1
Recv: ok
Recv: wait
Send: M105
Recv: ok
Recv: T:0
Recv: wait
Changing monitoring state from 'Operational' to 'Closed'
Changing monitoring state from 'Offline' to 'Detecting serial port'
Connecting to: /dev/ttyACM0
Changing monitoring state from 'Detecting serial port' to 'Opening serial port'
Connection closed, closing down monitor
Connected to: Serial<id=0x2221570, open=True>(port='/dev/ttyACM0', baudrate=115200, bytesize=8, parity='N', stopbits=1, timeout=None, xonxoff=False, rtscts=False, dsrdtr=False), starting monitor
Starting baud rate detection
Changing monitoring state from 'Opening serial port' to 'Detecting baudrate'
Recv: wait
Trying baudrate: 250000
Send: M110
Recv: e1
Changing monitoring state from 'Detecting baudrate' to 'Closed'
Changing monitoring state from 'Offline' to 'Detecting serial port'
Failed to autodetect serial port
Changing monitoring state from 'Detecting serial port' to 'Error: Failed to autodetect serial port.'
Changing monitoring state from 'Error: Failed to autodetect serial port.' to 'Detecting serial port'
Serial port list: ['/dev/ttyACM1']
Connecting to: /dev/ttyACM1
Error while connecting to /dev/ttyACM1: 'Timeout'
Changing monitoring state from 'Detecting serial port' to 'Error: Failed to autodetect serial port, please set it manually.'
Failed to autodetect serial port, please set it manually.
Connecting to: /dev/ttyACM1
Changing monitoring state from 'Offline' to 'Opening serial port'
Connected to: Serial<id=0x22cb7d0, open=True>(port='/dev/ttyACM1', baudrate=115200, bytesize=8, parity='N', stopbits=1, timeout=None, xonxoff=False, rtscts=False, dsrdtr=False), starting monitor
Changing monitoring state from 'Opening serial port' to 'Connecting'
Send: M110
Unexpected error while reading serial port, please consult octoprint.log for details: SerialException: 'device reports readiness to read but returned no data (device disconnected or multiple access on port?)' @ comm.py:_readline:1419
Changing monitoring state from 'Connecting' to 'Error: SerialException: 'device reports readiness to read but returned no data (device disconnected or multiple access on port?)' @ comm.py:_readline:1419'
Connection closed, closing down monitor
Connecting to: /dev/ttyACM1
Changing monitoring state from 'Offline' to 'Opening serial port'
Connected to: Serial<id=0x22c31d0, open=True>(port='/dev/ttyACM1', baudrate=115200, bytesize=8, parity='N', stopbits=1, timeout=None, xonxoff=False, rtscts=False, dsrdtr=False), starting monitor
Changing monitoring state from 'Opening serial port' to 'Connecting'
Send: M110
Recv: e1
Recv: ok REPETIER_PROTOCOL:2 FIRMWARE_NAME:Micro3D FIRMWARE_VERSION:2016012501 MACHINE_TYPE:The_Micro X-SERIAL_NUMBER:GR15061901050040
Changing monitoring state from 'Connecting' to 'Operational'
Send: M105
Send: M21
Recv: ok
Recv: T:0
Send: M117
Send: M114
Recv: ok ZV:0 S:128
Recv: ok  Z:0.0000
Send: M619 S12 T4
Recv: ok  PT:12 DT:1054905749
Send: M619 S16 T4
Send: M619 S20 T4
Recv: ok  PT:16 DT:1058642330
Send: M619 S24 T4
Recv: ok  PT:20 DT:1024106757
Send: M619 S28 T4
Recv: ok  PT:24 DT:1059309502
Send: M619 S32 T4
Recv: ok  PT:28 DT:-1087395415
Send: M619 S40 T1
Recv: ok  PT:32 DT:-1077801397
Send: M619 S41 T1
Recv: ok  PT:40 DT:67
Send: M619 S70 T4
Recv: ok  PT:41 DT:165
Send: M619 S74 T4
Recv: ok  PT:70 DT:0
Send: M619 S78 T4
Recv: ok  PT:74 DT:0
Send: M619 S82 T4
Recv: ok  PT:78 DT:0
Send: M619 S86 T4
Recv: ok  PT:82 DT:0
Send: M619 S94 T4
Recv: ok  PT:86 DT:0
Send: M619 S102 T4
Recv: ok  PT:94 DT:1153138688
Send: M619 S106 T4
Recv: ok  PT:102 DT:1153138688
Send: M619 S110 T4
Recv: ok  PT:106 DT:1153138688
Send: M619 S114 T4
Recv: ok  PT:110 DT:1114636288
Send: M619 S118 T4
Recv: ok  PT:114 DT:1120665600
Send: M619 S98 T1
Recv: ok  PT:118 DT:1135869952
Send: M420 T100
Recv: ok  PT:98 DT:1
Recv: ok
Connection closed, closing down monitor
Recv: wait
Send: M105
Recv: ok
Recv: T:0
Recv: wait ...................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................


Then, I was able to go to “control” and click on Calibrate bed Z0. It took a long time with long enough delays that I thought it was frozen several times, but eventually I got the complete message (it worked!). I then went in to the terminal and saw where the long “wait” period was (same as the very end, listed above) and starting writing this email. In the time it took me to copy/paste and write all the above, the connection failed and I lost everything that happened after the long “wait”. Once Octopi was back up, I copied what was in the terminal, but did not need the long “wait” that was there before, so I am guessing that the re-connection process wiped that out. Here is what I had *after* the reconnection process:

Send: M619 S41 T1
Recv: ok  PT:40 DT:67
Send: M619 S70 T4
Recv: ok  PT:41 DT:165
Send: M619 S74 T4
Recv: ok  PT:70 DT:0
Send: M619 S78 T4
Recv: ok  PT:74 DT:0
Send: M619 S82 T4
Recv: ok  PT:78 DT:0
Recv: ok  PT:82 DT:0
Send: M619 S86 T4
Send: M619 S94 T4
Recv: ok  PT:86 DT:0
Send: M619 S102 T4
Recv: ok  PT:94 DT:1153138688
Send: M619 S106 T4
Recv: ok  PT:102 DT:1153138688
Send: M619 S110 T4
Recv: ok  PT:106 DT:1153138688
Send: M619 S114 T4
Recv: ok  PT:110 DT:1114636288
Send: M619 S118 T4
Recv: ok  PT:114 DT:1120665600
Send: M619 S98 T1
Recv: ok  PT:118 DT:1135869952
Send: M420 T100
Recv: ok  PT:98 DT:1
Recv: ok
Recv: wait
Send: M105
Recv: ok
Recv: T:0
Recv: wait
Changing monitoring state from 'Operational' to 'Closed'
Connection closed, closing down monitor
Changing monitoring state from 'Offline' to 'Detecting serial port'
Connecting to: /dev/ttyACM0
Changing monitoring state from 'Detecting serial port' to 'Opening serial port'
Connected to: Serial<id=0x1fc0b30, open=True>(port='/dev/ttyACM0', baudrate=115200, bytesize=8, parity='N', stopbits=1, timeout=None, xonxoff=False, rtscts=False, dsrdtr=False), starting monitor
Starting baud rate detection
Changing monitoring state from 'Opening serial port' to 'Detecting baudrate'
Trying baudrate: 250000
Send: M110
Recv: e1
Changing monitoring state from 'Detecting baudrate' to 'Closed'
Changing monitoring state from 'Offline' to 'Detecting serial port'
Connection closed, closing down monitor
Connecting to: /dev/ttyACM0
Changing monitoring state from 'Detecting serial port' to 'Opening serial port'
Connected to: Serial<id=0x2299270, open=True>(port='/dev/ttyACM0', baudrate=115200, bytesize=8, parity='N', stopbits=1, timeout=None, xonxoff=False, rtscts=False, dsrdtr=False), starting monitor
Starting baud rate detection
Changing monitoring state from 'Opening serial port' to 'Detecting baudrate'
Recv: e1
Recv: wait
Trying baudrate: 250000
Send: M110
Recv: e1
Recv: e1
Recv: ok
Changing monitoring state from 'Detecting baudrate' to 'Operational'
Send: M21
Unexpected error while writing to serial port: SerialException: 'write failed: [Errno 5] Input/output error' @ comm.py:_doSendWithoutChecksum:1752
Connection closed, closing down monitor
Changing monitoring state from 'Operational' to 'Error: SerialException: 'write failed: [Errno 5] Input/output error' @ comm.py:_doSendWithoutChecksum:1752'
Closing down send loop
Connecting to: /dev/ttyACM1
Changing monitoring state from 'Offline' to 'Opening serial port'
Connected to: Serial<id=0x221fb10, open=True>(port='/dev/ttyACM1', baudrate=115200, bytesize=8, parity='N', stopbits=1, timeout=None, xonxoff=False, rtscts=False, dsrdtr=False), starting monitor
Changing monitoring state from 'Opening serial port' to 'Connecting'
Send: M110
Unexpected error while reading serial port, please consult octoprint.log for details: SerialException: 'device reports readiness to read but returned no data (device disconnected or multiple access on port?)' @ comm.py:_readline:1419
Changing monitoring state from 'Connecting' to 'Error: SerialException: 'device reports readiness to read but returned no data (device disconnected or multiple access on port?)' @ comm.py:_readline:1419'
Connection closed, closing down monitor
Connecting to: /dev/ttyACM0
Changing monitoring state from 'Offline' to 'Opening serial port'
Connected to: Serial<id=0x221f1f0, open=True>(port='/dev/ttyACM0', baudrate=115200, bytesize=8, parity='N', stopbits=1, timeout=None, xonxoff=False, rtscts=False, dsrdtr=False), starting monitor
Changing monitoring state from 'Opening serial port' to 'Connecting'
Send: M110
Recv: e1
Recv: ok REPETIER_PROTOCOL:2 FIRMWARE_NAME:Micro3D FIRMWARE_VERSION:2016012501 MACHINE_TYPE:The_Micro X-SERIAL_NUMBER:GR15061901050040
Changing monitoring state from 'Connecting' to 'Operational'
Send: M105
Send: M21
Recv: ok
Recv: T:0
Send: M117
Recv: ok ZV:0 S:128
Send: M114
Recv: ok  Z:0.0000
Send: M619 S12 T4
Send: M619 S16 T4
Recv: ok  PT:12 DT:1054905749
Send: M619 S20 T4
Recv: ok  PT:16 DT:1058642330
Send: M619 S24 T4
Recv: ok  PT:20 DT:1024106757
Send: M619 S28 T4
Recv: ok  PT:24 DT:1059309502
Send: M619 S32 T4
Recv: ok  PT:28 DT:-1087395415
Send: M619 S40 T1
Recv: ok  PT:32 DT:-1077801397
Send: M619 S41 T1
Recv: ok  PT:40 DT:67
Send: M619 S70 T4
Recv: ok  PT:41 DT:165
Send: M619 S74 T4
Recv: ok  PT:70 DT:0
Send: M619 S78 T4
Recv: ok  PT:74 DT:0
Send: M619 S82 T4
Recv: ok  PT:78 DT:0
Send: M619 S86 T4
Recv: ok  PT:82 DT:0
Send: M619 S94 T4
Recv: ok  PT:86 DT:0
Send: M619 S102 T4
Recv: ok  PT:94 DT:1153138688
Send: M619 S106 T4
Recv: ok  PT:102 DT:1153138688
Send: M619 S110 T4
Recv: ok  PT:106 DT:1153138688
Send: M619 S114 T4
Recv: ok  PT:110 DT:1114636288
Send: M619 S118 T4
Recv: ok  PT:114 DT:1120665600
Send: M619 S98 T1
Recv: ok  PT:118 DT:1135869952
Send: M420 T100
Recv: ok  PT:98 DT:1
Recv: ok
Recv: wait
Send: M105
Recv: ok
Recv: T:0
Recv: wait
Changing monitoring state from 'Operational' to 'Closed'
Changing monitoring state from 'Offline' to 'Detecting serial port'
Connecting to: /dev/ttyACM0
Changing monitoring state from 'Detecting serial port' to 'Opening serial port'
Connection closed, closing down monitor
Connected to: Serial<id=0x2221570, open=True>(port='/dev/ttyACM0', baudrate=115200, bytesize=8, parity='N', stopbits=1, timeout=None, xonxoff=False, rtscts=False, dsrdtr=False), starting monitor
Starting baud rate detection
Changing monitoring state from 'Opening serial port' to 'Detecting baudrate'
Recv: wait
Trying baudrate: 250000
Send: M110
Recv: e1
Changing monitoring state from 'Detecting baudrate' to 'Closed'
Changing monitoring state from 'Offline' to 'Detecting serial port'
Failed to autodetect serial port
Changing monitoring state from 'Detecting serial port' to 'Error: Failed to autodetect serial port.'
Changing monitoring state from 'Error: Failed to autodetect serial port.' to 'Detecting serial port'
Serial port list: ['/dev/ttyACM1']
Connecting to: /dev/ttyACM1
Error while connecting to /dev/ttyACM1: 'Timeout'
Changing monitoring state from 'Detecting serial port' to 'Error: Failed to autodetect serial port, please set it manually.'
Failed to autodetect serial port, please set it manually.
Connecting to: /dev/ttyACM1
Changing monitoring state from 'Offline' to 'Opening serial port'
Connected to: Serial<id=0x22cb7d0, open=True>(port='/dev/ttyACM1', baudrate=115200, bytesize=8, parity='N', stopbits=1, timeout=None, xonxoff=False, rtscts=False, dsrdtr=False), starting monitor
Changing monitoring state from 'Opening serial port' to 'Connecting'
Send: M110
Unexpected error while reading serial port, please consult octoprint.log for details: SerialException: 'device reports readiness to read but returned no data (device disconnected or multiple access on port?)' @ comm.py:_readline:1419
Changing monitoring state from 'Connecting' to 'Error: SerialException: 'device reports readiness to read but returned no data (device disconnected or multiple access on port?)' @ comm.py:_readline:1419'
Connection closed, closing down monitor
Connecting to: /dev/ttyACM1
Changing monitoring state from 'Offline' to 'Opening serial port'
Connected to: Serial<id=0x22c31d0, open=True>(port='/dev/ttyACM1', baudrate=115200, bytesize=8, parity='N', stopbits=1, timeout=None, xonxoff=False, rtscts=False, dsrdtr=False), starting monitor
Changing monitoring state from 'Opening serial port' to 'Connecting'
Send: M110
Recv: e1
Recv: ok REPETIER_PROTOCOL:2 FIRMWARE_NAME:Micro3D FIRMWARE_VERSION:2016012501 MACHINE_TYPE:The_Micro X-SERIAL_NUMBER:GR15061901050040
Changing monitoring state from 'Connecting' to 'Operational'
Send: M105
Send: M21
Recv: ok
Recv: T:0
Send: M117
Send: M114
Recv: ok ZV:0 S:128
Recv: ok  Z:0.0000
Send: M619 S12 T4
Recv: ok  PT:12 DT:1054905749
Send: M619 S16 T4
Send: M619 S20 T4
Recv: ok  PT:16 DT:1058642330
Send: M619 S24 T4
Recv: ok  PT:20 DT:1024106757
Send: M619 S28 T4
Recv: ok  PT:24 DT:1059309502
Send: M619 S32 T4
Recv: ok  PT:28 DT:-1087395415
Send: M619 S40 T1
Recv: ok  PT:32 DT:-1077801397
Send: M619 S41 T1
Recv: ok  PT:40 DT:67
Send: M619 S70 T4
Recv: ok  PT:41 DT:165
Send: M619 S74 T4
Recv: ok  PT:70 DT:0
Send: M619 S78 T4
Recv: ok  PT:74 DT:0
Send: M619 S82 T4
Recv: ok  PT:78 DT:0
Send: M619 S86 T4
Recv: ok  PT:82 DT:0
Send: M619 S94 T4
Recv: ok  PT:86 DT:0
Send: M619 S102 T4
Recv: ok  PT:94 DT:1153138688
Send: M619 S106 T4
Recv: ok  PT:102 DT:1153138688
Send: M619 S110 T4
Recv: ok  PT:106 DT:1153138688
Send: M619 S114 T4
Recv: ok  PT:110 DT:1114636288
Send: M619 S118 T4
Recv: ok  PT:114 DT:1120665600
Send: M619 S98 T1
Recv: ok  PT:118 DT:1135869952
Send: M420 T100
Recv: ok  PT:98 DT:1
Recv: ok
Connection closed, closing down monitor
Recv: wait
Send: M105
Recv: ok
Recv: T:0
Recv: wait
Send: N0 M110
Send: N1 G90
Recv: ok 0
Send: N2 M109 S150
Recv: ok 1
Send: N3 M104 S0
Recv: T:0.9484
Recv: T:11.5178
Recv: T:23.3829
Recv: T:32.9258
Recv: T:40.8045
Recv: T:47.8973
Recv: T:55.1805
Recv: T:62.6619
Recv: T:69.3138
Recv: T:73.7521
Recv: T:78.2524
Recv: T:81.7584
Recv: T:89.9936
Recv: T:89.9936
Recv: T:94.7403
Recv: T:98.4674
Recv: T:103.3453
Recv: T:107.1905
Recv: T:112.2052
Recv: T:116.1740
Recv: T:116.1740
Recv: T:121.3316
Recv: T:125.4296
Recv: T:125.4296
Recv: T:130.7368
Recv: T:134.9701
Recv: T:139.2691
Recv: T:140.4334
Recv: T:140.4334
Recv: T:144.8087
Recv: T:144.8087
Recv: T:149.2529
Recv: ok 2
Send: N4 M107
Recv: ok 3
Recv: T:0
Send: N5 G30
Recv: ok 4
Send: N6 M65536
Send: M105
Send: M105
Send: M105
Recv: ok 5
Send: M105
Recv: T:0.0000
Recv: ok
Recv: T:0
Recv: ok
Recv: T:0
Recv: ok
Recv: T:0
Recv: ok
Recv: T:0
Recv: wait
Send: N0 M110
Recv: ok 0
Send: M117
Recv: ok ZV:1 S:3
Send: N1 M65536
Send: M105
Recv: ok
Recv: T:0
Recv: wait ...
And deja vu all over again. Disconnected and reconnected, with nothing touching/changing via the hardware, cables, set up, etc.



Thanks for your help!



James





On February 14, 2016 at 2:40:48 AM, donovan6000 (notifications@github.com) wrote:



What does OctoPrint's terminal tab show when this happens? You won't be able to go to that tab when the 'calibration in progress' message is showing, you'll need to refresh the webpage and then go to the controls tab.

**Comment by donovan6000** [comment]
It all looks normal. Does OctoPrint's log show any error? It's in ~/.octoprint/logs/octoprint.log

**Comment by donovan6000** [comment]
I'm probably going to close this issue in the next couple of days since no ones responded to it in awhile. Let me know if you still have any interest in testing/solving it.

**Comment by jctj** [comment]
Ugh - I *want* to but just bogged down so much at the moment. Please close it and when I get to fire the printer up again (with updated software, etc.) if there is still a problem I will let you know then. 

Thank you again for all the work you put into such a needed solution! Really, M3D should have done this (would be great if they paid you a gift or something…).

James

-- 
James Taylor
Sent with Airmail

On March 16, 2016 at 5:55:48 PM, donovan6000 (notifications@github.com) wrote:

I'm probably going to close this issue in the next couple of days since no ones responded to it in awhile. Let me know if you still have any interest in testing/solving it.

**Comment by donovan6000** [comment]
Ok
