### ISSUE TITLE
Wall size always 0.35

### ISSUE THREAD

**Issue by jbliesener** [donovan6000/M3D-Fio#81]
There seems to be an error in converting the profiles. The wall size is only one line width, generating too thin walls and lots of oozing.

The problem seems to be that `engineToProfile.py` does not use the `insetCount` parameter. The value is saved to the `lineCount` variable, but not used to calculate `wall_thickness`.

I'm not sure, but maybe, changing 

`output.write("wall_thickness = " + str(layer0extrusionWidth / 1000.0) + '\n')`

to 

`output.write("wall_thickness = " + str(extrusionWidth  * lineCount / 1000.0) + '\n')`

could solve the problem.

**Comment by donovan6000** [comment]
Ok, sounds right to me. The [devel branch](https://github.com/donovan6000/M3D-Fio/commit/5f599bd8b469824ef028718838f2af84522c45ea) now used the engineToProfile.py with you fix and changing the fill settings in the profile editor will also adjust the wall_thickness parameter.
