### ISSUE TITLE
When removing filament, pressing "no, haven't been extracted" causes it to wam up indefinitely

### ISSUE THREAD

**Issue by abbradar** [donovan6000/M3D-Fio#85]
See the title. I've ended up reconnecting the printer and restarting the whole process.

**Comment by donovan6000** [comment]
We might have fixed this in the [devel branch](https://github.com/donovan6000/M3D-Fio/tree/devel). Give it a try, and let me know if it's still an issue.
`https://github.com/donovan6000/M3D-Fio/archive/devel.zip`

**Comment by abbradar** [comment]
Yes, this is fixed -- even better, in release 0.27. Thanks!
