### ISSUE TITLE
Unhandled firmware error

### ISSUE THREAD

**Issue by Timelord73** [donovan6000/M3D-Fio#89]
This is the error I am getting and I have tried the trouble shooting and have no other COMS open open to any and all suggestions.

Changing monitoring state from 'Offline' to 'Detecting serial port'
Connecting to: COM6
Changing monitoring state from 'Detecting serial port' to 'Error: Connection error, see Terminal tab'
Unexpected error while connecting to serial port: AUTO SerialException: 'could not open port 'COM6': WindowsError(5, 'Access is denied.')' @ comm.py:_openSerial:1349 (hook m3dfio)

**Comment by donovan6000** [comment]
This should be fixed in the newest M3D Fio version. I just released V0.27 about an hour ago.

**Comment by Timelord73** [comment]
Do I have to download the whole program again or can I just get the updated addition.

**Comment by donovan6000** [comment]
You should be able to update M3D Fio from inside of OctoPrint's plugin manager. Go to the 'Software Update' tab in OctoPrint's settings, and it should show that an update is available for M3D Fio.

**Comment by Timelord73** [comment]
It is saying that is up to date at V 0.26 and no updates

**Comment by Timelord73** [comment]
Got it to work. Is there a manual or user guide I can use to reference?

**Comment by donovan6000** [comment]
There's no manual for M3D Fio. There's probably some manuals on using OctoPrint is you search around.
