### ISSUE TITLE
Calibrating before print can be disastrous if you don't monitor the calibration.

### ISSUE THREAD

**Issue by LogicalChaos** [donovan6000/M3D-Fio#90]
With the new support for "calibration before print" enabled, the second print with that setting failed, cosmetically damaging the printer.  This is not a problem with M3D-Fio, rather the OctoPrint video shows the M3D calibration obviously not working, and when the print head touches down to being printing, it's apparent the calibration was 5mm (or more) too low.  After cleaning up and re-calibrating, it prints just fine again.  Robust is not what you often hear with this printer, but it came through that print just fine, if not a little scarred.  Emergency stop works well.

You may want to put a caution on that radio button, to be cautious walking away.  I've used the calibration many times manually, and have never seen this type of failure before.

![img_2301](https://cloud.githubusercontent.com/assets/6620274/13201325/44de0b84-d829-11e5-9592-8e9cf7787c6e.png)
![img_2302](https://cloud.githubusercontent.com/assets/6620274/13201324/44c96f30-d829-11e5-8ba7-5e4e49f96848.png)

**Comment by donovan6000** [comment]
Alright, I added a caution next to the option and updated its tool tip to advise against leaving the printer unmonitored until after the print starts. Hopefully that doesn't happen too frequently. Their accelemoter is really sensitive, so it must have picked up some vibrations or something.
![caution](https://cloud.githubusercontent.com/assets/6620767/13201971/cf6e343c-d83c-11e5-9c88-b97d6093a424.png)

**Comment by LogicalChaos** [comment]
Looks good.  Wouldn't of saved me anyway, as I already ignore the "Dangerous" warning of ignoring print dimensions limitation because "I know what I'm doing" (obviously).  Maybe someone will pay attention to it though.
