### ISSUE TITLE
Where is model editor located?

### ISSUE THREAD

**Issue by abbradar** [donovan6000/M3D-Fio#91]
First -- I'm sorry for the very stupid question! I've been trying to find how to invoke Modify Model dialog for some time. From screenshot and description it looks like it can be opened when slicing a model, but I see only Modify Profile dialog (and also the first generic one). I've also looked around OctoPrint in general (M3D Fio settings, various tabs...) but haven't noticed even a mention. How can I open it? To be clear, I mean this window: https://raw.githubusercontent.com/donovan6000/M3D-Fio/master/images/model%20editor.png .

**Comment by ra100** [comment]
Hi, model editor is opened after you modify slicing profile. First you choose slicing profile, than you can modify it and after that you can modify model.

**Comment by abbradar** [comment]
Very strange, right after modifying a profile the model is just sliced and I don't have any following dialogs.

**Comment by abbradar** [comment]
Just to clarify: after this dialog:
![Modify Profile](https://raw.githubusercontent.com/donovan6000/M3D-Fio/master/images/profile%20editor.png)
when I click Slice, all dialogs are closed and sliced model is added to the files list.

**Comment by donovan6000** [comment]
Your web browsers doesn't support WebGL or doesn't have it enabled

Can you see a spinning cube [here](https://get.webgl.org/)?

**Comment by abbradar** [comment]
Huh, indeed -- Firefox has disabled WebGL support for me for some reason. After resetting `*context*` variables in `about:config` as was suggested [here](https://bbs.archlinux.org/viewtopic.php?id=207637) the cube appeared.

I would suggest adding a small warning to the "Modify Profile" dialog, like "Warning: WebGL is not supported, Model Editor is not enabled" -- how about this?

**Comment by donovan6000** [comment]
Sounds good to me. The next version will have a warning about skipping the model editor if WebGL is disabled/not detected
![skip](https://cloud.githubusercontent.com/assets/6620767/13216453/b3119fc0-d910-11e5-82f2-d0cb7441dc0d.png)

**Comment by abbradar** [comment]
Thanks!
