### ISSUE TITLE
Advanced Settings section cannot be opened

### ISSUE THREAD

**Issue by abbradar** [donovan6000/M3D-Fio#94]
![Profile editor](https://raw.githubusercontent.com/donovan6000/M3D-Fio/master/images/profile%20editor.png)

Here, Advanced Settings is hidden for me and the arrow doesn't do anything.

**Comment by donovan6000** [comment]
What web browser are you using? All of my development and testing happens in Google Chrome.

**Comment by abbradar** [comment]
It's Firefox 44. Interface in other places works fine. Sadly I don't understand anything in web development so I don't even know where to start by myself -- if you have time, please take a look.

**Comment by abbradar** [comment]
FWIW, Manual Settings works fine.

**Comment by donovan6000** [comment]
Ok, it's fixed now in the [devel branch](https://github.com/donovan6000/M3D-Fio/tree/devel). You can install it using OctoPrint's plugin manager by installing a plugin from this URL: `https://github.com/donovan6000/M3D-Fio/archive/devel.zip`

For some reason the click event wasn't being recognized there but the mousedown event was, so it was an easy fix. Usually Firefox conforms to web standards much better than Chrome, so maybe I just wasn't seeing something.

**Comment by abbradar** [comment]
It works, thanks.
